#!/bin/bash

set -e

# Create .config directory if not exists
[ -d ~/.config ] || mkdir ~/.config
[ -d ~/.local/bin/ ] || mkdir -p ~/.local/bin/

# Install tools
pkg_mgr=""
command -v yum >&/dev/null && pkg_mgr="yum"
command -v dnf >&/dev/null && pkg_mgr="dnf"
command -v apt-get >&/dev/null && pkg_mgr="apt-get"

function install_tool() {
	tools=()
	for tool in $1; do
		command -v "$tool" &>/dev/null || \
			tools+=("$tool")
	done

	[[ "${#tools[*]}" -gt 0 ]] && \
		(sudo "$pkg_mgr" update -y;sudo "$pkg_mgr" install ${tools[*]} -y)
}
echo "Using package manager: $pkg_mgr"
install_tool "git curl zsh tmux alacritty neovim"

# Initialize ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Link directory and files
function link() {
	ln -s "$1" "$2"
}

ln -s $(pwd)/config/nvim ~/.config/nvim/
ln -s $(pwd)/config/tmux ~/.config/tmux/
ln -s $(pwd)/config/alacritty ~/.config/alacritty/
ln -s $(pwd)/local/bin/* ~/.local/bin/
ln -s $(pwd)/zshrc ~/.zshrc
